services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase2'
      - 'MYSQL_PASSWORD=secret2'
      - 'MYSQL_ROOT_PASSWORD=verysecret2'
      - 'MYSQL_USER=myuser2'
    ports:
      - '3306'
