name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to latest version supporting Node.js 20

    - name: Set up JDK 11
      uses: actions/setup-java@v3  # Updated to latest version
      with:
        java-version: '11'
        distribution: 'adopt'  # Specify the distribution, e.g., 'adopt', 'temurin', etc.

    - name: Build with Maven
      run: mvn -f backend/pom.xml clean install

    - name: Run tests
      run: mvn -f backend/pom.xml test

  frontend-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to latest version

    - name: Ensure frontend directory exists
      run: mkdir -p frontend  # Ensure the frontend directory exists

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Updated to latest version
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: frontend

    - name: Build project
      run: npm run build
      working-directory: frontend

    - name: Run tests
      run: npm test
      working-directory: frontend

  cpp-service-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to latest version

    - name: Install dependencies
      run: sudo apt-get install -y build-essential cmake

    - name: Build C++ service
      run: |
        cd cpp-service
        mkdir -p build  # Ensure build directory exists
        cd build
        cmake ..
        make

    - name: Run tests
      run: ./cpp-service/build/tests  # Ensure this path is correct for your tests
